# Generated by Django 3.2 on 2021-09-04 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProviderServiceArea',
        ),
    ]
